name: CI
on: 
  workflow_dispatch:
  push:
    branches:
     - master #here we choose to deploy only when a push is detected on the main branch
    paths:
      - src/frontend/**
     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Use your bucket region here
        
    
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./src/frontend/ s3://cloud-resume-challenge-frontend-bucket-001 --delete
    - name: Deploy to cloudfront
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.PERSONAL_SITE_CF_ID }} --paths "/*"
